<?php

declare(strict_types=1);

$cover = '/assets/images/post-cover.svg';

return [
    'categories' => [
        [
            'name' => 'PHP',
            'slug' => 'php',
            'description' => 'Plain PHP, application architecture, and backend development.',
        ],
        [
            'name' => 'Databases',
            'slug' => 'databases',
            'description' => 'MySQL schema design, queries, indexes, and data access.',
        ],
        [
            'name' => 'Frontend',
            'slug' => 'frontend',
            'description' => 'Templates, SCSS, and accessible user interfaces.',
        ],
        [
            'name' => 'DevOps',
            'slug' => 'devops',
            'description' => 'Docker, Nginx, local development, and deployment.',
        ],
    ],
    'posts' => [
        [
            'image' => $cover,
            'title' => 'Building a Regex Router in Plain PHP',
            'slug' => 'building-regex-router-plain-php',
            'description' => 'A small router can support named parameters, method checks, and useful HTTP errors.',
            'body' => 'A router does not need a framework to stay readable. Start by separating route registration from dispatching, anchor every regular expression, and pass named matches to controller actions. Clear 404 and 405 responses make the behavior predictable for both users and developers.',
            'views_count' => 184,
            'published_at' => '2026-08-01 09:00:00',
            'categories' => ['php'],
        ],
        [
            'image' => $cover,
            'title' => 'Rendering Reusable Pages with Smarty',
            'slug' => 'rendering-reusable-pages-smarty',
            'description' => 'Layouts and focused page templates keep presentation code out of controllers.',
            'body' => 'Smarty provides a clear boundary between PHP and HTML. A shared layout can contain navigation, metadata, and common assets while each page template focuses on its own content. Controllers only prepare data and choose the response status.',
            'views_count' => 132,
            'published_at' => '2026-08-02 10:30:00',
            'categories' => ['php', 'frontend'],
        ],
        [
            'image' => $cover,
            'title' => 'Safe MySQL Connections with PDO',
            'slug' => 'safe-mysql-connections-pdo',
            'description' => 'Validated environment settings and native prepared statements form a solid PDO baseline.',
            'body' => 'Connection settings should come from the environment and never be committed as production secrets. PDO should throw exceptions, return associative rows, and use native prepared statements. A small connection factory keeps these decisions consistent across the application.',
            'views_count' => 251,
            'published_at' => '2026-08-03 08:15:00',
            'categories' => ['php', 'databases'],
        ],
        [
            'image' => $cover,
            'title' => 'Designing Many-to-Many Blog Categories',
            'slug' => 'designing-many-to-many-blog-categories',
            'description' => 'A junction table lets one article belong to several categories without duplicating data.',
            'body' => 'The post_categories table contains one post identifier and one category identifier. A composite primary key prevents duplicate relationships, while foreign keys protect consistency. Cascade deletion removes relationship rows when either parent record is deleted.',
            'views_count' => 97,
            'published_at' => '2026-08-04 11:45:00',
            'categories' => ['php', 'databases'],
        ],
        [
            'image' => $cover,
            'title' => 'Indexes for Blog Sorting and Pagination',
            'slug' => 'indexes-blog-sorting-pagination',
            'description' => 'Useful indexes reduce the work required for publication-date and popularity sorting.',
            'body' => 'Indexes should follow real query patterns. A blog commonly sorts by published_at or views_count and joins posts through category identifiers. The execution plan should be checked as the amount of content grows instead of adding indexes to every column.',
            'views_count' => 223,
            'published_at' => '2026-08-05 14:00:00',
            'categories' => ['databases'],
        ],
        [
            'image' => $cover,
            'title' => 'Compiling SCSS without Adding Node.js',
            'slug' => 'compiling-scss-without-nodejs',
            'description' => 'A PHP SCSS compiler keeps the development stack small and still supports modular styles.',
            'body' => 'When a project already uses Composer, scssphp can compile SCSS without introducing npm. Source files remain split by purpose, while a generated CSS file is available to the production image. Atomic replacement avoids serving a partially written stylesheet.',
            'views_count' => 168,
            'published_at' => '2026-08-06 09:20:00',
            'categories' => ['php', 'frontend'],
        ],
        [
            'image' => $cover,
            'title' => 'A Small Docker Environment for PHP',
            'slug' => 'small-docker-environment-php',
            'description' => 'Nginx, PHP-FPM, and MySQL are enough for a reproducible local blog environment.',
            'body' => 'Each container should have one clear responsibility. Health checks allow services to wait for their dependencies, and named volumes preserve database and runtime data. A development override can mount source files without changing the production image.',
            'views_count' => 305,
            'published_at' => '2026-08-07 16:10:00',
            'categories' => ['devops', 'php'],
        ],
        [
            'image' => $cover,
            'title' => 'Connecting Nginx to PHP-FPM',
            'slug' => 'connecting-nginx-php-fpm',
            'description' => 'A narrow Nginx configuration exposes only public assets and the front controller.',
            'body' => 'The public directory should be the only web document root. Requests for missing files are forwarded to index.php, while application source and configuration remain unreachable. FastCGI parameters tell PHP-FPM which script and request path to process.',
            'views_count' => 144,
            'published_at' => '2026-08-08 12:00:00',
            'categories' => ['devops'],
        ],
        [
            'image' => $cover,
            'title' => 'Counting Article Views Correctly',
            'slug' => 'counting-article-views-correctly',
            'description' => 'An atomic database update prevents lost increments when several readers open one article.',
            'body' => 'Reading a counter and writing the incremented value in two queries creates a race condition. Updating views_count with views_count plus one lets MySQL perform the operation atomically. The refreshed value can then be selected for display.',
            'views_count' => 389,
            'published_at' => '2026-08-09 18:30:00',
            'categories' => ['php', 'databases'],
        ],
        [
            'image' => $cover,
            'title' => 'Stable Pagination with MySQL',
            'slug' => 'stable-pagination-mysql',
            'description' => 'A secondary unique sort key keeps pages stable when primary values are equal.',
            'body' => 'Sorting only by publication date can produce unstable pages when two posts share the same timestamp. Adding the post identifier as a secondary order makes the result deterministic. Limit and offset are then calculated from a validated page number.',
            'views_count' => 276,
            'published_at' => '2026-08-10 07:50:00',
            'categories' => ['php', 'databases'],
        ],
        [
            'image' => $cover,
            'title' => 'Finding Related Articles by Category',
            'slug' => 'finding-related-articles-category',
            'description' => 'Shared categories provide a simple and explainable relevance signal.',
            'body' => 'Related posts can be ranked by the number of categories they share with the current article. The current post must be excluded, and publication date can break ties. Limiting the query to three results keeps the article page focused.',
            'views_count' => 198,
            'published_at' => '2026-08-11 13:25:00',
            'categories' => ['php', 'databases'],
        ],
        [
            'image' => $cover,
            'title' => 'Preparing a Compose App for Production',
            'slug' => 'preparing-compose-app-production',
            'description' => 'Production images should contain dependencies and generated assets without development tools.',
            'body' => 'A multi-stage Docker build installs Composer packages in an environment matching the runtime extensions. Development-only dependencies stay outside the final image, while compiled CSS is copied with the application. Runtime directories receive explicit writable permissions.',
            'views_count' => 342,
            'published_at' => '2026-08-12 15:40:00',
            'categories' => ['devops', 'php'],
        ],
    ],
];
